name: Unit Test
on: [ push ]
jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['7.2', '7.3', '7.4', '8.0', '8.1']
        laravel-version: ['^6', '^7', '^8', '^9']
        exclude:
          - php-version: 7.2
            laravel-version: ^8
          - php-version: 7.2
            laravel-version: ^9
          - php-version: 7.3
            laravel-version: ^9
          - php-version: 7.4
            laravel-version: ^9
          - php-version: 8.0
            laravel-version: ^6
          - php-version: 8.0
            laravel-version: ^7
          - php-version: 8.1
            laravel-version: ^6
          - php-version: 8.1
            laravel-version: ^7
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --no-progress
      - name: Install laravel
        run: composer require illuminate/contracts:${{ matrix.laravel-version }} --no-interaction --prefer-dist --no-progress
      - name: Run unit tests
        run: vendor/bin/phpunit

